### PR TITLE
Generate README.rst dynamically

### PR DESCRIPTION
**Pull request by walro**
And added release how-to.

### CODE REVIEW

**Comment by roback** [comment]
If you check that the `TRAVIS` environment variable is set you can avoid having to install pypandoc on Travis. I can't come up with a better solution than this :)

``` diff
diff --git a/setup.py b/setup.py
index 2eaeda1..37dc31e 100644
--- a/setup.py
+++ b/setup.py
@@ -3,7 +3,6 @@
 '''The setup and build script for the twingly-search library.'''

 import os
-import pypandoc

 from setuptools import setup, find_packages

@@ -12,6 +11,11 @@ def read(*paths):
     with open(os.path.join(*paths), 'r') as f:
         return f.read()

+readme_rst = ""
+if not os.environ.has_key('TRAVIS'):
+    import pypandoc
+    readme_rst = pypandoc.convert('README.md', 'rst')
+
 setup(
     name='twingly-search',
     version='1.0.2',
@@ -21,7 +25,7 @@ setup(
     url='https://github.com/twingly/twingly-search-api-python',
     keywords='twingly',
     description='Python library for Twingly Search API',
-    long_description=pypandoc.convert('README.md', 'rst'),
+    long_description=readme_rst,
     packages=find_packages(exclude=['tests*']),
     install_requires=['future', 'requests'],
     classifiers=[
```

Tested this locally:

``` shell
$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    import pypandoc
ImportError: No module named pypandoc

$ TRAVIS=true python setup.py install
running install
running bdist_egg
...
```

**Comment by walro** [comment]
I am also interested in, as I mentioned IRL, to be able to install the library without having to install pandoc and pyandoc first. I am 99% sure that `python setup.py install` would fail as it is now (if you don't have the dependencies).

**Comment by dentarg** [comment]
What about the other way around.

It's `python setup.py register` that need pandoc. Let's wrap `python setup.py register` in `bin/publish` and if you run that, we run the conversion, otherwise we set `long_description` to empty string or whatever.

**Comment by roback** [comment]
Or like this:

``` python
readme_rst = ""
if len(sys.argv) > 1 and sys.argv[1] == "register":
    import pypandoc
    readme_rst = pypandoc.convert('README.md', 'rst')
```

**Comment by walro** [comment]
I thought @dentarg meant something like this, which I think I like over the argument check

``` diff
diff --git a/.travis.yml b/.travis.yml
index df7b8d0..7b9a3f3 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,15 +1,11 @@
 language: python
 sudo: false
-addons:
-  apt_packages:
-    - pandoc

 python:
   - "2.7"
   - "3.5"

 install:
-  - pip install pypandoc
   - travis_retry pip install .
   - pip install -r test_requirements.txt

diff --git a/README.md b/README.md
index 3eb2567..7283f27 100644
--- a/README.md
+++ b/README.md
@@ -72,14 +72,14 @@ To learn more about the capabilities of the API, please read the [Twingly Search

 ## Release

-You'll need pandoc to convert the Markdown README to reStructuredText:
+You will need pandoc to convert README.md to reStructuredText:

     brew install pandoc
     pip install pypandoc

-To publish:
+To publish to PyPi:

-    python setup.py register
+    bin/publish

 ## License

diff --git a/bin/publish b/bin/publish
new file mode 100755
index 0000000..75988d0
--- /dev/null
+++ b/bin/publish
@@ -0,0 +1,3 @@
+#!/bin/sh
+
+GENERATE_RST=true python setup.py register
diff --git a/setup.py b/setup.py
index 2eaeda1..4606bfb 100644
--- a/setup.py
+++ b/setup.py
@@ -3,7 +3,6 @@
 '''The setup and build script for the twingly-search library.'''

 import os
-import pypandoc

 from setuptools import setup, find_packages

@@ -12,6 +11,11 @@ def read(*paths):
     with open(os.path.join(*paths), 'r') as f:
         return f.read()

+readme_rst = ""
+if os.environ.has_key('GENERATE_RST'):
+    import pypandoc
+    readme_rst = pypandoc.convert('README.md', 'rst')
+
 setup(
     name='twingly-search',
     version='1.0.2',
@@ -21,7 +25,7 @@ setup(
     url='https://github.com/twingly/twingly-search-api-python',
     keywords='twingly',
     description='Python library for Twingly Search API',
-    long_description=pypandoc.convert('README.md', 'rst'),
+    long_description=readme_rst,
     packages=find_packages(exclude=['tests*']),
     install_requires=['future', 'requests'],
     classifiers=[
```

**Comment by dentarg** [comment]
Sure :)

I think the variable could be named `long_description` rather than `readme_rst` and maybe default to something else than empty string? Not sure it if matters for anything, but if it does... :)

**Comment by walro** [comment]
> I think the variable could be named long_description rather than readme_rst and maybe default to something else than empty string? Not sure it if matters for anything, but if it does... :)

:+1:

**Comment by dentarg** [comment]
Yeah, I agree with @walro, with `GENERATE_RST` it should be easier to understand and it's more explicit. And a like the wrapper script :) (easy to remember than the `python setup.py register` harang

**Comment by walro** [comment]
Let me incorporate the variable change and default case change and see how that'll work out. Gimme a sec.

**Comment by walro** [comment]
@dentarg and @roback any comments?

**Comment by roback** [comment]
The `read` method in `setup.py` could be removed as it isn't used anymore, but other than that I think it looks good :)

**Comment by bearburger** [comment]
Sorry for late just was a bit busy but I think you could just remove Markdown version and keep only RST one. I just checked and looks like Github supports `README.rst` files as main project description and there is not much differences in case if you haven't plan to make it real documentation page. RST is required only because PyPI does not understand Markdown :-(

**Comment by walro** [comment]
> Sorry for late just was a bit busy but I think you could just remove Markdown version and keep only RST one. I just checked and looks like Github supports README.rst files as main project description and there is not much differences in case if you haven't plan to make it real documentation page. RST is required only because PyPI does not understand Markdown :-(

Yeah, we thought of that solution too, but we use Markdown everywhere so we thought it was better to keep the MD file and convert to RST on the fly.

Thanks for your input though!

**Pull request merged**
