### PR TITLE
Make sure instance variables are declared in __init__

### LINKED ISSUE #23: Instance variables not declared correctly
Instance variables should be declared inside the `__init__` method. We declare variables directly in the class, which makes them class variables: https://docs.python.org/2/tutorial/classes.html#class-and-instance-variables

Example: https://github.com/twingly/twingly-search-api-python/blob/master/twingly_search/query.py#L23-L27

I have updated the `Post` class already (in 3251010640e4323abe6ea4c6bd215d3d19ba787a).

### PR DESCRIPTION
**Pull request by roback**
Declaring them directly in the class makes them class variables.

fix #23

### CODE REVIEW

**Comment by dentarg** [comment]
should we add the tests we talked about? check that the "empty" object has the instance variables we want, or is it too much?

**Comment by roback** [comment]
> should we add the tests we talked about? check that the "empty" object has the instance variables we want, or is it too much?

Yes, Im on it :)

**Comment by dentarg** [comment]
great :)

**Comment by roback** [comment]
> > should we add the tests we talked about? check that the "empty" object has the instance variables we want, or is it too much?
> 
> Yes, Im on it :)

I think I changed my mind, maby its too much :). The user never sees the "empty" objects themselves. The only object the user should create themselves is the `Client`.

**Comment by dentarg** [comment]
Sure, let's be happy with this. LGTM

**Pull request merged**
